<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright(C) (2023) Sapper Inc. (open.source at zyient dot io)
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<!DOCTYPE customers [
  <!ELEMENT customers (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (_id?,customerName?,contactLastName?,contactFirstName?,phone?,addressLine1?,addressLine2?,city?,state?,postalCode?,country?,salesRepEmployeeNumber?,creditLimit?)+>
  <!ELEMENT _id (#PCDATA)>
  <!ELEMENT customerName (#PCDATA)>
  <!ELEMENT contactLastName (#PCDATA)>
  <!ELEMENT contactFirstName (#PCDATA)>
  <!ELEMENT phone (#PCDATA)>
  <!ELEMENT addressLine1 (#PCDATA)>
  <!ELEMENT addressLine2 (#PCDATA)>
  <!ELEMENT city (#PCDATA)>
  <!ELEMENT state (#PCDATA)>
  <!ELEMENT postalCode (#PCDATA)>
  <!ELEMENT country (#PCDATA)>
  <!ELEMENT salesRepEmployeeNumber (#PCDATA)>
  <!ELEMENT creditLimit (#PCDATA)>
]>
<customers>
  <DATA_RECORD>
    <_id>16</_id>
    <customerName>93864832-445d-4845-87df-e07f1b295e25, First [16]</customerName>
    <contactLastName>93864832-445d-4845-87df-e07f1b295e25</contactLastName>
    <contactFirstName>First [16]</contactFirstName>
    <phone>+1045640040</phone>
    <addressLine1>Address 1: 0a05b8f6-a13b-42bf-8f45-4a1d00e72f6a</addressLine1>
    <addressLine2>Address 2: fe637ad2-a121-4d06-a935-4daa89807e55</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>652950</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-1,198,205,008</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>17</_id>
    <customerName>53ff8212-7a8b-4c0e-ac25-d2bc7876ee7f, First [17]</customerName>
    <contactLastName>53ff8212-7a8b-4c0e-ac25-d2bc7876ee7f</contactLastName>
    <contactFirstName>First [17]</contactFirstName>
    <phone>+1782224382</phone>
    <addressLine1>Address 1: 48424e85-b1eb-4641-aa30-ecdea46c0786</addressLine1>
    <addressLine2>Address 2: 3f38de09-498d-4056-bb42-8e2801cc07e8</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>772116</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>414,812,982</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>18</_id>
    <customerName>90f8e981-faf6-46c6-b391-bbb48d975e82, First [18]</customerName>
    <contactLastName>90f8e981-faf6-46c6-b391-bbb48d975e82</contactLastName>
    <contactFirstName>First [18]</contactFirstName>
    <phone>+1990858715</phone>
    <addressLine1>Address 1: dcf665ef-6fd3-4ee4-ac26-3201cde0590d</addressLine1>
    <addressLine2>Address 2: eb8b19db-d7eb-4d1a-94ee-3b76f4cf1d73</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>877873</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-1,495,664,492</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>19</_id>
    <customerName>74437c3e-a9ce-4d90-9396-1b0ac4c1f5e8, First [19]</customerName>
    <contactLastName>74437c3e-a9ce-4d90-9396-1b0ac4c1f5e8</contactLastName>
    <contactFirstName>First [19]</contactFirstName>
    <phone>+1742337897</phone>
    <addressLine1>Address 1: 194d635b-c44d-4fd2-808b-c4a9d5c59025</addressLine1>
    <addressLine2>Address 2: 1c00e7bd-db9f-4408-8ad8-5df284ad9df4</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>687044</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>824,127,501</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>20</_id>
    <customerName>a0127bf5-43a6-4c08-a15c-47bb304196d5, First [20]</customerName>
    <contactLastName>a0127bf5-43a6-4c08-a15c-47bb304196d5</contactLastName>
    <contactFirstName>First [20]</contactFirstName>
    <phone>+1625531150</phone>
    <addressLine1>Address 1: ad3ae941-72b4-487f-811d-57c573df81de</addressLine1>
    <addressLine2>Address 2: ba745a05-e456-43d2-b622-8edc896fb36c</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>41480</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-1,011,843,276</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>21</_id>
    <customerName>ba8f2d6e-836a-41f5-8a72-ebc45f61a4cd, First [21]</customerName>
    <contactLastName>ba8f2d6e-836a-41f5-8a72-ebc45f61a4cd</contactLastName>
    <contactFirstName>First [21]</contactFirstName>
    <phone>+1744602873</phone>
    <addressLine1>Address 1: 011e6226-a355-44a4-801a-bd2abb791c2c</addressLine1>
    <addressLine2>Address 2: e7e30596-154e-489a-aabd-31694e24e2af</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>184329</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>332,520,778</salesRepEmployeeNumber>
    <creditLimit>0.13</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>22</_id>
    <customerName>bcec1159-07d1-425f-8a9c-8e0a8cbc13f9, First [22]</customerName>
    <contactLastName>bcec1159-07d1-425f-8a9c-8e0a8cbc13f9</contactLastName>
    <contactFirstName>First [22]</contactFirstName>
    <phone>+1816458972</phone>
    <addressLine1>Address 1: 7ccfe6ee-21b9-4019-b79c-16eaddb2cd05</addressLine1>
    <addressLine2>Address 2: 13a0d599-83b5-4c85-9c08-38630f959201</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>194882</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>767,377,856</salesRepEmployeeNumber>
    <creditLimit>0.1</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>23</_id>
    <customerName>487330eb-95ad-4eaf-8c42-93678674f80a, First [23]</customerName>
    <contactLastName>487330eb-95ad-4eaf-8c42-93678674f80a</contactLastName>
    <contactFirstName>First [23]</contactFirstName>
    <phone>+2116823625</phone>
    <addressLine1>Address 1: 885deb26-518d-459c-8a0e-04f5ddb3eead</addressLine1>
    <addressLine2>Address 2: f24efbd4-d0c7-4472-a106-ae0d7588ed75</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>523466</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-392,290,225</salesRepEmployeeNumber>
    <creditLimit>0.43</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>24</_id>
    <customerName>5f2f18c1-5bab-423f-bfc6-e943979ed0c0, First [24]</customerName>
    <contactLastName>5f2f18c1-5bab-423f-bfc6-e943979ed0c0</contactLastName>
    <contactFirstName>First [24]</contactFirstName>
    <phone>+1597869789</phone>
    <addressLine1>Address 1: ce898ed2-8321-43a4-9f8d-3a1b1a0a0804</addressLine1>
    <addressLine2>Address 2: b39a9756-2fda-46c8-aeb0-145005c70de7</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>584098</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-1,428,312,367</salesRepEmployeeNumber>
    <creditLimit>0.03</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>25</_id>
    <customerName>a7c01910-e340-4a0e-be1e-f5c10547659a, First [25]</customerName>
    <contactLastName>a7c01910-e340-4a0e-be1e-f5c10547659a</contactLastName>
    <contactFirstName>First [25]</contactFirstName>
    <phone>+1394243399</phone>
    <addressLine1>Address 1: 784334fc-c947-467e-b967-ab922c07e5f6</addressLine1>
    <addressLine2>Address 2: db580138-5246-4f75-85bf-bc4b7124d6f3</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>980713</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>795,701,437</salesRepEmployeeNumber>
    <creditLimit>0.91</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>32</_id>
    <customerName>acb32641-d32c-4e9e-9088-63b6256a8661, First [32]</customerName>
    <contactLastName>acb32641-d32c-4e9e-9088-63b6256a8661</contactLastName>
    <contactFirstName>First [32]</contactFirstName>
    <phone>+1227647703</phone>
    <addressLine1>Address 1: f8af66cb-fd41-448b-90f4-8b5802719993</addressLine1>
    <addressLine2>Address 2: 63073b7d-91c7-41d5-b7ec-e432d7133029</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>969656</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,763,457,811</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>33</_id>
    <customerName>98cd69f2-4212-4f06-b719-7efb1a30c91d, First [33]</customerName>
    <contactLastName>98cd69f2-4212-4f06-b719-7efb1a30c91d</contactLastName>
    <contactFirstName>First [33]</contactFirstName>
    <phone>+1152204996</phone>
    <addressLine1>Address 1: fc79e9f6-8e54-45e8-8077-a6d46279e760</addressLine1>
    <addressLine2>Address 2: 6ad15c78-9417-49d4-83f6-0ad7cb72db09</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>453767</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,154,941,156</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>34</_id>
    <customerName>926fe8cd-3428-4d0c-889e-1cdb62a34f31, First [34]</customerName>
    <contactLastName>926fe8cd-3428-4d0c-889e-1cdb62a34f31</contactLastName>
    <contactFirstName>First [34]</contactFirstName>
    <phone>+1405399005</phone>
    <addressLine1>Address 1: 73f16db4-7146-4a02-a766-809e182c9d2e</addressLine1>
    <addressLine2>Address 2: bf5cd50d-2d2e-4026-9f5e-e881225fcaa3</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>625932</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,384,932,553</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>35</_id>
    <customerName>0422c374-fbde-4bad-b597-6c201cfa7b5a, First [35]</customerName>
    <contactLastName>0422c374-fbde-4bad-b597-6c201cfa7b5a</contactLastName>
    <contactFirstName>First [35]</contactFirstName>
    <phone>+1930847506</phone>
    <addressLine1>Address 1: d6ffd09e-4caa-452c-8faa-6bb5dcc33052</addressLine1>
    <addressLine2>Address 2: 3d493c4a-3c42-4d87-9262-5bcc1f270bdd</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>282257</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-1,235,012,888</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>36</_id>
    <customerName>92d73c1e-13c8-4195-a54e-b51ca27d2c98, First [36]</customerName>
    <contactLastName>92d73c1e-13c8-4195-a54e-b51ca27d2c98</contactLastName>
    <contactFirstName>First [36]</contactFirstName>
    <phone>+1923565244</phone>
    <addressLine1>Address 1: 81128747-27e7-472a-8896-7ae67c5dcef8</addressLine1>
    <addressLine2>Address 2: 97b17093-e3ef-4e37-9ac6-e437aa46c5c8</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>91610</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,731,350,541</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>37</_id>
    <customerName>dccb5010-9f54-4405-a8a1-01ed8a17a4f6, First [37]</customerName>
    <contactLastName>dccb5010-9f54-4405-a8a1-01ed8a17a4f6</contactLastName>
    <contactFirstName>First [37]</contactFirstName>
    <phone>+1939073245</phone>
    <addressLine1>Address 1: 24fac8c1-3b3f-44c8-8522-03df21f9a5fe</addressLine1>
    <addressLine2>Address 2: 1f9fe76d-ea48-49f2-bff9-746776a97aeb</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>385917</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>2,145,039,713</salesRepEmployeeNumber>
    <creditLimit>0.22</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>38</_id>
    <customerName>ce6dfc58-9596-4df7-aa8e-f64d54a306ab, First [38]</customerName>
    <contactLastName>ce6dfc58-9596-4df7-aa8e-f64d54a306ab</contactLastName>
    <contactFirstName>First [38]</contactFirstName>
    <phone>+1293993412</phone>
    <addressLine1>Address 1: f963dbdf-4c32-44b6-ad85-5a90ab06426e</addressLine1>
    <addressLine2>Address 2: b8153839-8541-4250-a972-dec1243c43c4</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>77422</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,396,828,126</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>39</_id>
    <customerName>1c7570b2-1277-4685-9e64-fba0f00c22d7, First [39]</customerName>
    <contactLastName>1c7570b2-1277-4685-9e64-fba0f00c22d7</contactLastName>
    <contactFirstName>First [39]</contactFirstName>
    <phone>+1439082549</phone>
    <addressLine1>Address 1: 9704398c-932f-42fe-a46f-61bb3baa0f30</addressLine1>
    <addressLine2>Address 2: 00cb5573-cf31-47bb-986c-6113cb1a8c52</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>933064</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-1,367,117,698</salesRepEmployeeNumber>
    <creditLimit>0.03</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>40</_id>
    <customerName>9711b10b-00b1-422c-9bb3-d0eca0b72835, First [40]</customerName>
    <contactLastName>9711b10b-00b1-422c-9bb3-d0eca0b72835</contactLastName>
    <contactFirstName>First [40]</contactFirstName>
    <phone>+2088992309</phone>
    <addressLine1>Address 1: 7ae3d7ae-45b8-4c0d-ac92-095b236ac7aa</addressLine1>
    <addressLine2>Address 2: 5ce7c6eb-51bd-438f-8c90-ba3b44296208</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>769854</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>417,752,866</salesRepEmployeeNumber>
    <creditLimit>0.53</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>41</_id>
    <customerName>2adecd86-38d7-4cec-b640-d54f80da91b2, First [41]</customerName>
    <contactLastName>2adecd86-38d7-4cec-b640-d54f80da91b2</contactLastName>
    <contactFirstName>First [41]</contactFirstName>
    <phone>+1077067287</phone>
    <addressLine1>Address 1: b7116df1-6906-41c9-8ce2-c5693f06a94b</addressLine1>
    <addressLine2>Address 2: b01b364c-bfd1-4d08-ad06-83633a9c4417</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>544039</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,584,237,004</salesRepEmployeeNumber>
    <creditLimit>0.85</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>48</_id>
    <customerName>d5d72f0f-6150-448a-a16c-2f8cea2bcc58, First [48]</customerName>
    <contactLastName>d5d72f0f-6150-448a-a16c-2f8cea2bcc58</contactLastName>
    <contactFirstName>First [48]</contactFirstName>
    <phone>+2088407410</phone>
    <addressLine1>Address 1: cb908177-441b-48d4-a6a9-d8bc0db4159f</addressLine1>
    <addressLine2>Address 2: 248aca80-c722-4f32-9db1-c1f1125ba98a</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>682274</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>920,605,422</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>49</_id>
    <customerName>c62777a7-6c36-40a0-8fc7-4ae2fad3b19a, First [49]</customerName>
    <contactLastName>c62777a7-6c36-40a0-8fc7-4ae2fad3b19a</contactLastName>
    <contactFirstName>First [49]</contactFirstName>
    <phone>+1056843463</phone>
    <addressLine1>Address 1: 78e76cfd-293e-4767-99e6-4757e64d5552</addressLine1>
    <addressLine2>Address 2: d3073dd2-83e4-49c8-8d50-680555499fd2</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>469652</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>761,859,274</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>50</_id>
    <customerName>4d9089aa-ebf0-43b3-8281-a1f7c01b3a4e, First [50]</customerName>
    <contactLastName>4d9089aa-ebf0-43b3-8281-a1f7c01b3a4e</contactLastName>
    <contactFirstName>First [50]</contactFirstName>
    <phone>+2024440975</phone>
    <addressLine1>Address 1: d1fa989d-a46a-4914-b955-4385f48e5985</addressLine1>
    <addressLine2>Address 2: 25b4051b-5bef-4487-8ebd-76d9f630405f</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>510650</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-1,612,772,932</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>51</_id>
    <customerName>070da6ba-f4e1-4f14-be36-2a8ca0cc7027, First [51]</customerName>
    <contactLastName>070da6ba-f4e1-4f14-be36-2a8ca0cc7027</contactLastName>
    <contactFirstName>First [51]</contactFirstName>
    <phone>+2012467786</phone>
    <addressLine1>Address 1: 8c2ede05-0963-4322-9e7d-c7333e007100</addressLine1>
    <addressLine2>Address 2: 08b1540c-c4da-41a5-8c2f-596de3cd8760</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>198296</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,682,234,493</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>52</_id>
    <customerName>93662931-e383-407b-80e5-558360cd9c6a, First [52]</customerName>
    <contactLastName>93662931-e383-407b-80e5-558360cd9c6a</contactLastName>
    <contactFirstName>First [52]</contactFirstName>
    <phone>+1079950561</phone>
    <addressLine1>Address 1: fac4472c-bc52-403d-bf6c-aac7d6eca3a3</addressLine1>
    <addressLine2>Address 2: 00c63d99-279f-40f0-af1d-9eb95860be21</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>153384</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>2,045,603,097</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>58</_id>
    <customerName>16b44742-34f3-4d0d-828c-ac25d6ee8353, First [58]</customerName>
    <contactLastName>16b44742-34f3-4d0d-828c-ac25d6ee8353</contactLastName>
    <contactFirstName>First [58]</contactFirstName>
    <phone>+1068455123</phone>
    <addressLine1>Address 1: f86545a7-978e-4363-aec5-0c804eeeaaa6</addressLine1>
    <addressLine2>Address 2: bc95c391-37da-411b-b98a-4a1761920846</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>898165</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-363,813,522</salesRepEmployeeNumber>
    <creditLimit>0.62</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>59</_id>
    <customerName>15d0767f-0a65-4aa2-8836-2b679057d560, First [59]</customerName>
    <contactLastName>15d0767f-0a65-4aa2-8836-2b679057d560</contactLastName>
    <contactFirstName>First [59]</contactFirstName>
    <phone>+1152066591</phone>
    <addressLine1>Address 1: a0e4a4cc-b9ca-4811-9cf2-2786b9410e4f</addressLine1>
    <addressLine2>Address 2: d896ca87-09b6-4813-9dbc-33885a0741e8</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>541292</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-2,000,364,310</salesRepEmployeeNumber>
    <creditLimit>0.94</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>60</_id>
    <customerName>f041dff3-6ddd-40d0-b321-fd9c5c9d3d61, First [60]</customerName>
    <contactLastName>f041dff3-6ddd-40d0-b321-fd9c5c9d3d61</contactLastName>
    <contactFirstName>First [60]</contactFirstName>
    <phone>+1106141910</phone>
    <addressLine1>Address 1: 1a06bbe3-1918-4764-acc6-3f6e35bd470c</addressLine1>
    <addressLine2>Address 2: d69f92c5-f703-4893-b759-44b5f7a73453</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>856523</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>841,683,169</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>61</_id>
    <customerName>6d90753a-d89f-4115-bf50-e56a9d421d69, First [61]</customerName>
    <contactLastName>6d90753a-d89f-4115-bf50-e56a9d421d69</contactLastName>
    <contactFirstName>First [61]</contactFirstName>
    <phone>+1680487735</phone>
    <addressLine1>Address 1: e4508f16-9419-4107-a68a-ee8458c35d44</addressLine1>
    <addressLine2>Address 2: d9468a4d-470f-4574-950c-8ad4175f7ff8</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>782252</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>306,447,014</salesRepEmployeeNumber>
    <creditLimit>0.13</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>62</_id>
    <customerName>ac766878-0cea-4ef8-abe8-360d675d08e6, First [62]</customerName>
    <contactLastName>ac766878-0cea-4ef8-abe8-360d675d08e6</contactLastName>
    <contactFirstName>First [62]</contactFirstName>
    <phone>+1261510542</phone>
    <addressLine1>Address 1: aedf671f-0cbe-4477-8015-249b89d2a1a0</addressLine1>
    <addressLine2>Address 2: d2fec7ba-cbed-44c9-a29b-90bc456471f4</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>613879</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,687,943,626</salesRepEmployeeNumber>
    <creditLimit>0.03</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>64</_id>
    <customerName>a09cc875-837e-4f01-8eed-a9cb9b04fdd3, First [64]</customerName>
    <contactLastName>a09cc875-837e-4f01-8eed-a9cb9b04fdd3</contactLastName>
    <contactFirstName>First [64]</contactFirstName>
    <phone>+1401302634</phone>
    <addressLine1>Address 1: 22a302a8-f1ed-4080-886b-54738a33a9c2</addressLine1>
    <addressLine2>Address 2: 21aaea20-2326-4a46-82c7-e0594eb60827</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>678966</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-1,307,349,399</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>65</_id>
    <customerName>d22a8c8a-94b0-45d7-b384-a04724aca56e, First [65]</customerName>
    <contactLastName>d22a8c8a-94b0-45d7-b384-a04724aca56e</contactLastName>
    <contactFirstName>First [65]</contactFirstName>
    <phone>+1966342716</phone>
    <addressLine1>Address 1: bda7fea6-eaf6-4bfd-8d34-27efd996688e</addressLine1>
    <addressLine2>Address 2: 2256d609-19af-4a6e-a41b-6aad8a17be48</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>774460</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,939,380,687</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>66</_id>
    <customerName>9967bef0-e55b-4f32-b8a2-1ef0ad4cade9, First [66]</customerName>
    <contactLastName>9967bef0-e55b-4f32-b8a2-1ef0ad4cade9</contactLastName>
    <contactFirstName>First [66]</contactFirstName>
    <phone>+1340310283</phone>
    <addressLine1>Address 1: 02bff323-1681-4f49-b84a-0ae5c8530772</addressLine1>
    <addressLine2>Address 2: 3cef14f3-53d2-45f8-8a35-8e24123f7dc6</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>876965</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,737,051,724</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>67</_id>
    <customerName>eb18e4c3-ccc0-40f7-b1d3-6347c09edd83, First [67]</customerName>
    <contactLastName>eb18e4c3-ccc0-40f7-b1d3-6347c09edd83</contactLastName>
    <contactFirstName>First [67]</contactFirstName>
    <phone>+1394827523</phone>
    <addressLine1>Address 1: b70f07cb-c1cd-4a27-9348-0b69859d9f44</addressLine1>
    <addressLine2>Address 2: 6b97987c-b398-4948-b646-a0c034862178</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>331771</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-1,948,809,742</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>68</_id>
    <customerName>d061a914-dd3b-47e3-8cad-94f828d05806, First [68]</customerName>
    <contactLastName>d061a914-dd3b-47e3-8cad-94f828d05806</contactLastName>
    <contactFirstName>First [68]</contactFirstName>
    <phone>+1864563321</phone>
    <addressLine1>Address 1: deb8cfab-6fd7-464a-af62-1e8f5ca1ffaa</addressLine1>
    <addressLine2>Address 2: 5af59047-ff55-4e36-9f38-a6bcb6d033b9</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>684723</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,942,958,049</salesRepEmployeeNumber>
    <creditLimit>0</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>74</_id>
    <customerName>3c1e2fbd-bb13-4445-85bb-ad492612e27a, First [74]</customerName>
    <contactLastName>3c1e2fbd-bb13-4445-85bb-ad492612e27a</contactLastName>
    <contactFirstName>First [74]</contactFirstName>
    <phone>+1188671125</phone>
    <addressLine1>Address 1: 525b2c01-2eaf-4784-b942-f6aa92cbd03d</addressLine1>
    <addressLine2>Address 2: a0ebbc5f-efd2-4ef4-9aed-1d16b6302806</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>76593</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>454,687,070</salesRepEmployeeNumber>
    <creditLimit>0.43</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>75</_id>
    <customerName>fdb08e19-e51f-4b3a-a85e-ba90d29d51a5, First [75]</customerName>
    <contactLastName>fdb08e19-e51f-4b3a-a85e-ba90d29d51a5</contactLastName>
    <contactFirstName>First [75]</contactFirstName>
    <phone>+1036431248</phone>
    <addressLine1>Address 1: 8e2ed845-33a9-47f5-b1ae-5d4c9bf82ebc</addressLine1>
    <addressLine2>Address 2: 7499ce94-da06-477a-b8ca-03e94ff0f105</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>159902</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>1,472,800,009</salesRepEmployeeNumber>
    <creditLimit>0.28</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>76</_id>
    <customerName>4d53e791-b4fb-421d-bdb1-5d4d7aa1f4db, First [76]</customerName>
    <contactLastName>4d53e791-b4fb-421d-bdb1-5d4d7aa1f4db</contactLastName>
    <contactFirstName>First [76]</contactFirstName>
    <phone>+1427301345</phone>
    <addressLine1>Address 1: 78b641bf-2e64-4fcb-a9e8-5ee91105ae5b</addressLine1>
    <addressLine2>Address 2: 4b442871-a700-4d63-a68a-cf7a6b92f60c</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>66752</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-2,146,421,843</salesRepEmployeeNumber>
    <creditLimit>0.26</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>77</_id>
    <customerName>7ceffca1-1e25-4292-8848-23cf97150a9d, First [77]</customerName>
    <contactLastName>7ceffca1-1e25-4292-8848-23cf97150a9d</contactLastName>
    <contactFirstName>First [77]</contactFirstName>
    <phone>+1345084971</phone>
    <addressLine1>Address 1: 37fed728-9cf4-4a4c-a305-262f4f06b86b</addressLine1>
    <addressLine2>Address 2: a0a65cc4-4e7c-4e87-ba07-4a6b85ab7de2</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>454418</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>2,090,867,045</salesRepEmployeeNumber>
    <creditLimit>0.86</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>78</_id>
    <customerName>620fb145-38c0-4723-9855-4c6858b244ba, First [78]</customerName>
    <contactLastName>620fb145-38c0-4723-9855-4c6858b244ba</contactLastName>
    <contactFirstName>First [78]</contactFirstName>
    <phone>+1063190974</phone>
    <addressLine1>Address 1: 36073fb3-bcd9-4d4d-8e44-2fc89ce5214d</addressLine1>
    <addressLine2>Address 2: e2765b59-cd16-41e5-a6fa-2c0cbde5c5f6</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>929053</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-31,376,574</salesRepEmployeeNumber>
    <creditLimit>0.36</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>79</_id>
    <customerName>f985d498-c767-426a-8d2f-430172bf509e, First [79]</customerName>
    <contactLastName>f985d498-c767-426a-8d2f-430172bf509e</contactLastName>
    <contactFirstName>First [79]</contactFirstName>
    <phone>+2139490518</phone>
    <addressLine1>Address 1: f0d565d9-a814-432e-8983-f1222262b247</addressLine1>
    <addressLine2>Address 2: b2dac051-3862-4d7e-a98a-6a3e40d73070</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>532479</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-1,954,130,176</salesRepEmployeeNumber>
    <creditLimit>0.29</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>80</_id>
    <customerName>4c93c98f-00d8-4e78-ab5b-0b1ce93c2b41, First [80]</customerName>
    <contactLastName>4c93c98f-00d8-4e78-ab5b-0b1ce93c2b41</contactLastName>
    <contactFirstName>First [80]</contactFirstName>
    <phone>+1215821145</phone>
    <addressLine1>Address 1: 9910af4a-ea46-4b20-9709-fceac27fd51d</addressLine1>
    <addressLine2>Address 2: 98bc3ad8-4a51-4914-a83b-db5a09c573b8</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>
    <postalCode>413253</postalCode>
    <country>India</country>
    <salesRepEmployeeNumber>-50,844,765</salesRepEmployeeNumber>
    <creditLimit>0.03</creditLimit>
  </DATA_RECORD>
  <DATA_RECORD>
    <_id>81</_id>
    <customerName>61dded29-fb92-438f-a89b-7015edd8e4bc, First [81]</customerName>
    <contactLastName>61dded29-fb92-438f-a89b-7015edd8e4bc</contactLastName>
    <contactFirstName>First [81]</contactFirstName>
    <phone>+1935310491</phone>
    <addressLine1>Address 1: 6ef0429b-4106-4134-ad89-ccf60c922bbd</addressLine1>
    <addressLine2>Address 2: 25dcd912-e39b-48a5-ad4f-7290a3c5b455</addressLine2>
    <city>Bangalore</city>
    <state>KA</state>